package exception_nestedtrycatch;



public class Main {
	public static void main(String[]args)
	{
		System.out.println("the exception we got is :");
		nestedtrycatch.check();
	}

}
